### ISSUE TITLE
Clicking 'Add Candidates' in 'Add event candidate' window does not automatically close window or update table

### ISSUE THREAD

**Issue by samo115** [TOMToolkit/tom_nonlocalizedevents#20] opened 2023-06-09 13:15 UTC
I was looking at adding targets to a specific superevent using the button 'Add Candidate from Existing Target'. This throws open a new window with all the targets in the database. If I click one or more and then press 'Add Candidates' it doesn't do anything other than grey out the 'Add Candidates' button. To exit I have to close the window with the 'X' in the top right corner. I would have expected the window to close after pressing the 'Add Candidates' button.

After closing the window, the targets do not immediately appear on the table 'Active Candidates', but only do so if I refresh the page.

Perhaps this is all working as intended, but I just wanted to check as it didn't seem intuitive to me.

Thank you,

Sam

**Comment by jnation3406** [comment] 2023-06-13 22:54
Thanks for reporting this! I'll look into it and try to fix those issues. I believe we want it to work how you expect, so these two things you reported are bugs.

**Comment by jnation3406** [comment] 2023-06-15 21:47
@samo115 I have tried to reproduce the issue and best I can tell, you must have already had one or more of the selected targets created as a Candidate to get things to happen the way you described. In that case, adding them again silently fails (since you can't have duplicate candidates), and the add candidates button greys out but the modal doesn't close, just like you described. I'll work on fixing this so you get a suitable error displayed when that is the case, or just grey out the add candidates button when you have a target selected that is already a candidate... 

When I create or select a new target and then click add candidate from it, the modal does close for me as expected, and the candidates list is also immediately updated (without needing refresh). If that doesn't happen for you, even with a completely new target that you are sure is not an existing candidate, then please let me know, and if possible, look in your browsers web development console and let me know if you see an error occur when you click add candidates when it fails.

**Comment by jnation3406** [comment] 2023-06-21 17:03
Fixed in 0.7.7

**Closed by jnation3406** 2023-06-21 17:03 UTC
